### ISSUE TITLE
Footer appearance in mobile view

### ISSUE THREAD

**Issue by ujjwalkirti** [ujjwalkirti/helping-you-through-client#6]
The mobile view of the footer is looking quite clumsy and not user friendly.
![image](https://github.com/ujjwalkirti/helping-you-through/assets/64329707/1bbd1556-bb56-4417-a838-e7bedc79e664)
Please correct the same.
My suggestions:
- Don't divide the links into two different columns rather let them remain in a single column stacked over each other.
- Instead of a big bold contact us text, show all the socials icon with respect to theme colors.

**Comment by XFRCSD45** [comment]
![Screenshot 2023-08-20 133039](https://github.com/ujjwalkirti/helping-you-through/assets/108056620/c221682a-db44-4f93-8466-9183ba7ece15)
Fixed footer
